

server:
  port: 8762
spring:
  application:
    name: eureka-client-user

eureka:
  instance:
    # 设置应用实例id
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      # 设置eureka实例地址 admin:123456@
      defaultZone: http://localhost:8761/eureka