server:
    port: 8761

spring:
    application:
        name: eureka-server
# 关闭登录验证
#  security:admin:123456@
#    user:
#      name: admin
#      password: 123456

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
        register-with-eureka: false
        # 由于注册中心的职责就是维护服务示例,它并不需要去检索服务,所以也设置为false
        fetch-registry: false
        serviceUrl:
            # 使用Eureka服务器进行身份验证
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka