server:
  port: 8764
spring:
  application:
    name: eureka-client-movie-feign
eureka:
  instance:
    # 设置应用实例id
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      # 设置eureka实例地址
      defaultZone: http://localhost:8761/eureka